### ISSUE TITLE
Some bugs and suggestion

### ISSUE THREAD

**Issue by DataFancy** [yuchaojiang/CODEX2#1]
Line 11 and Line 25 in qc.R:
        You can replace end(ref) - start(ref)+1 by width(ref), for ref in of type IRranges
Line 67-68 in normalize.R:
        Offset might be L[s,] , not log(L[s,]), because L[,] is already the logarithm of (Nmat * fhat * betahatmat)   
        as in line 54
Line 92 in codex_targeted.R:
        The qcObj here is created across all chromosomes,  but when call the qc function in qc.R
        it seems that your qc function is for one chromosome, as in line 24,"rep(chr, length(ref))"
        so when applied to targeted sequencing, we should alter the qc.R in the package
        from "rep(chr, length(ref))" to 'chr' in line 24 and call it with 'chr.all' in condex_targeted.R

**Comment by yuchaojiang** [comment]
Thanks very much! All bugs are fixed and pushed. Much appreciated.

**Comment by DataFancy** [comment]
Thanks for your acceptance and I have a little more to say.
You can add a line before Line 91 in codex2_targeted.R
'chr = chr.all'
and call function qc with chr
then it will look more consistent

**Comment by yuchaojiang** [comment]
Thanks. Just updated.
