### ISSUE TITLE
some questions about CODEX2

### ISSUE THREAD

**Issue by zhoupersonal** [yuchaojiang/CODEX2#10]
Dear Dr.Jiang,
   I am a student from China.I'm using CODEX2 to analyze copy number changes in human samples by target capture sequencing, but I am so confused by the bad results.I didn't make correct input files and there's no online tutorial of target capture sequencing.Therefore ,there are several  questions I hope you could help me out :
   1.how the bam files are made?Could you tell me if the way bam file of target capture sequencing data are made is the same as the WES?Are they only sorted?What are the requirements for the  same batch of tested bam files e.g  the difference of the read depth ?
   2.how's the bed files cooked?I have the exact position of the capture region of target capture sequencing.
   3.In addition,I don't know why the result shows that the duplicate and the  deletion exist on the same chromosome of  the same sample with high quality.
   Thank you very much in advance.

Best regards,
 Ziying Zhou

**Comment by yuchaojiang** [comment]
Hi,

See my reply below.

Yuchao

On Mar 26, 2019, at 4:12 AM, zhoupersonal <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Dr.Jiang,
I am a student from China.I'm using CODEX2 to analyze copy number changes in human samples by target capture sequencing, but I am so confused by the bad results.I didn't make correct input files and there's no online tutorial of target capture sequencing.Therefore ,there are several questions I hope you could help me out :
1.how the bam files are made?Could you tell me if the way bam file of target capture sequencing data are made is the same as the WES?Are they only sorted?What are the requirements for the same batch of tested bam files e.g the difference of the read depth ?

One bam per sample. Bams should be sorted and indexed. The upstream processing is the same for WES and targeted sequencing.

2.how's the bed files cooked?I have the exact position of the capture region of target capture sequencing.

Bed file has three column: chr, start position, and end position for each target.

3.In addition,I don't know why the result shows that the duplicate and the deletion exist on the same chromosome of the same sample with high quality.

Not sure what you meant but deletions can duplications can happen on the same chromosome within the same sample.

Thank you very much in advance.


Best regards,
Ziying Zhou
