### ISSUE TITLE
CODEX2 targeted Error: subscript out of bounds

### ISSUE THREAD

**Issue by vigneshravi** [yuchaojiang/CODEX2#11]
I am trying to run CODEX2 on couple of targeted resequencing samples. the bed file is broken down into intervals of 250 basepairs for the regions of interest. I got the targeted demo code from git and initiated the run. Below is my log and error that I ran into. Any help understanding this error and fixing it would be great! 

Thanks!

`Getting GC content for chr 1
Getting GC content for chr 10
Getting GC content for chr 11
Getting GC content for chr 12
Getting GC content for chr 13
Getting GC content for chr 14
Getting GC content for chr 15
Getting GC content for chr 16
Getting GC content for chr 17
Getting GC content for chr 18
Getting GC content for chr 19
Getting GC content for chr 2
Getting GC content for chr 20
Getting GC content for chr 21
Getting GC content for chr 22
Getting GC content for chr 3
Getting GC content for chr 4
Getting GC content for chr 5
Getting GC content for chr 6
Getting GC content for chr 7
Getting GC content for chr 8
Getting GC content for chr 9
Getting GC content for chr X
Getting GC content for chr Y
Getting mappability for chr1
Getting mappability for chr10
Getting mappability for chr11
Getting mappability for chr12
Getting mappability for chr13
Getting mappability for chr14
Getting mappability for chr15
Getting mappability for chr16
Getting mappability for chr17
Getting mappability for chr18
Getting mappability for chr19
Getting mappability for chr2
Getting mappability for chr20
Getting mappability for chr21
Getting mappability for chr22
Getting mappability for chr3
Getting mappability for chr4
Getting mappability for chr5
Getting mappability for chr6
Getting mappability for chr7
Getting mappability for chr8
Getting mappability for chr9
Getting mappability for chrX
Getting mappability for chrY

Getting coverage for sample Sample1: read length 97.
Getting coverage for sample Sample2: read length 97.
Error in Y[, 1:5] : subscript out of bounds
Calls: head
Execution halted
`

**Comment by yuchaojiang** [comment]
Cannot help you with the limited info you provided. Can you send you script with step by step output?

Sent from my iPad

On Apr 23, 2019, at 4:00 PM, Vignesh Ravichandran <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to run CODEX2 on couple of targeted resequencing samples. the bed file is broken down into intervals of 250 basepairs for the regions of interest. I got the targeted demo code from git and initiated the run. Below is my log and error that I ran into. Any help understanding this error and fixing it would be great!

Thanks!

`Getting GC content for chr 1
Getting GC content for chr 10
Getting GC content for chr 11
Getting GC content for chr 12
Getting GC content for chr 13
Getting GC content for chr 14
Getting GC content for chr 15
Getting GC content for chr 16
Getting GC content for chr 17
Getting GC content for chr 18
Getting GC content for chr 19
Getting GC content for chr 2
Getting GC content for chr 20
Getting GC content for chr 21
Getting GC content for chr 22
Getting GC content for chr 3
Getting GC content for chr 4
Getting GC content for chr 5
Getting GC content for chr 6
Getting GC content for chr 7
Getting GC content for chr 8
Getting GC content for chr 9
Getting GC content for chr X
Getting GC content for chr Y
Getting mappability for chr1
Getting mappability for chr10
Getting mappability for chr11
Getting mappability for chr12
Getting mappability for chr13
Getting mappability for chr14
Getting mappability for chr15
Getting mappability for chr16
Getting mappability for chr17
Getting mappability for chr18
Getting mappability for chr19
Getting mappability for chr2
Getting mappability for chr20
Getting mappability for chr21
Getting mappability for chr22
Getting mappability for chr3
Getting mappability for chr4
Getting mappability for chr5
Getting mappability for chr6
Getting mappability for chr7
Getting mappability for chr8
Getting mappability for chr9
Getting mappability for chrX
Getting mappability for chrY

Getting coverage for sample Sample1: read length 97.
Getting coverage for sample Sample2: read length 97.
Error in Y[, 1:5] : subscript out of bounds
Calls: head
Execution halted
`

**Comment by vigneshravi** [comment]
Here is the code I ran. The last line of the code is where the error occurs.

`library(CODEX2)
##########################################################
# Initialization
##########################################################
bamdir=as.matrix(read.table('testbamlist.txt'))
sampname=as.matrix(read.table('testsamplelist.txt'))
bedFile='IM468genes_split250BP_forCODEX.bed'
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, sampname = sampname, projectname = "CODEX2_demo")
bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
ref <- bambedObj$ref; projectname <- bambedObj$projectname

##########################################################
# Getting GC content and mappability
##########################################################
gc <- getgc(ref)
mapp <- getmapp(ref)

##########################################################
# Getting gene names, needed for targeted sequencing, here generating gene names in silico
##########################################################
gene=rep(NA,length(ref))
for(chr in as.matrix(unique(seqnames(ref)))){
  chr.index=which(seqnames(ref)==chr)
  gene[chr.index]=paste(chr,'_gene_',ceiling(chr.index/30),sep='')
}
values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene))

##########################################################
# Getting depth of coverage
##########################################################
coverageObj <- getcoverage(bambedObj, mapqthres = 20)
Y <- coverageObj$Y
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)
head(Y[,1:5])
`

Sample results of the CODEX2_demo_coverage.csv that got created
,Sample1,Sample2
1:2487704-2487954,52,25
1:2487955-2488204,710,339
1:2488205-2488454,264,119
1:2488455-2488704,1,1
1:2488705-2488954,7,6
1:2488955-2489204,587,308
1:2489205-2489454,691,374
1:2489455-2489704,79,76
1:2489705-2489954,574,367

**Comment by yuchaojiang** [comment]
It seems that you only calculated coverage for two samples. Y[,1:5] would be out of bound.

On Apr 23, 2019, at 4:15 PM, Vignesh Ravichandran <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the code I ran. The last line of the code is where the error occurs.

`library(CODEX2)
##########################################################

Initialization

##########################################################
#dirPath=getwd()
#bamFile <- list.files(dirPath, pattern = '*.bam$')
#bamdir <- file.path(dirPath, bamFile)
#sampname <- substr(bamFile,1,9)
#bedFile <- file.path(dirPath, "scWGA500kb.bed")
#bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile,

sampname = sampname, projectname = "CODEX2_demo")

#bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
#ref <- bambedObj$ref; projectname <- bambedObj$projectname

bamdir=as.matrix(read.table('/work/offit/NGSdata/IMPACT/Impact-A/Codex/testbamlist.txt'))
sampname=as.matrix(read.table('/work/offit/NGSdata/IMPACT/Impact-A/Codex/testsamplelist.txt'))
bedFile='/ifs/e63data/offitlab/IMPACT/GeneLists/IM468genes_split250BP_forCODEX.bed'
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, sampname = sampname, projectname = "CODEX2_demo")
bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
ref <- bambedObj$ref; projectname <- bambedObj$projectname

##########################################################

Getting GC content and mappability

##########################################################
gc <- getgc(ref)
mapp <- getmapp(ref)

##########################################################

Getting gene names, needed for targeted sequencing, here generating gene names in silico

##########################################################
gene=rep(NA,length(ref))
for(chr in as.matrix(unique(seqnames(ref)))){
chr.index=which(seqnames(ref)==chr)
gene[chr.index]=paste(chr,'gene',ceiling(chr.index/30),sep='')
}
values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene))

##########################################################

Getting depth of coverage

##########################################################
coverageObj <- getcoverage(bambedObj, mapqthres = 20)
Y <- coverageObj$Y
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)
head(Y[,1:5])
`

Sample results of the CODEX2_demo_coverage.csv that got created
,Sample1,Sample2 1:2487704-2487954,52,25 1:2487955-2488204,710,339 1:2488205-2488454,264,119 1:2488455-2488704,1,1 1:2488705-2488954,7,6 1:2488955-2489204,587,308 1:2489205-2489454,691,374 1:2489455-2489704,79,76 1:2489705-2489954,574,367

**Comment by vigneshravi** [comment]
Is there a minimum sample requirement or is it just a temporary output check?

Can I comment it and run the rest of the code?

**Comment by yuchaojiang** [comment]
No. CODEX2 cannot be run on two samples only… It needs at least 20 samples for the cross-sample normalization to work.

On Apr 23, 2019, at 4:32 PM, Vignesh Ravichandran <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a minimum sample requirement or is it just a temporary output check?

Can I comment it and run the rest of the code?

**Comment by vigneshravi** [comment]
Thank you so much for the quick response yesterday. I re-ran the code with 288 samples. Although I got past the previous error, I have the following error.

> Error in eval(quote(list(...)), env) :
>   argument "chri" is missing, with no default
> Calls: segment_targeted -> cbind -> standardGeneric -> eval -> eval -> eval
> Execution halted


I checked the coverage file and QC matrix file that got generated. There are no missing or infinite values. 

Below is the code.
`library(CODEX2)
########################################################## 
# Initialization
########################################################## bamdir=as.matrix(read.table('testbamlist.txt')) 
sampname=as.matrix(read.table('testsamplelist.txt'))
bedFile='IM468genes_split250BP_forCODEX.bed'
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, sampname = sampname, projectname = "CODEX2_demo") bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname ref <- bambedObj$ref; projectname <- bambedObj$projectname

##########################################################
# Getting GC content and mappability
##########################################################
gc <- getgc(ref)
mapp <- getmapp(ref)

##########################################################
# Getting gene names, needed for targeted sequencing, here generating gene names in silico
##########################################################
gene=rep(NA,length(ref))
for(chr in as.matrix(unique(seqnames(ref)))){
  chr.index=which(seqnames(ref)==chr)
  gene[chr.index]=paste(chr,'_gene_',ceiling(chr.index/30),sep='')
}
values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene))

##########################################################
# Getting depth of coverage
##########################################################
coverageObj <- getcoverage(bambedObj, mapqthres = 20)
Y <- coverageObj$Y
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)
head(Y[,1:5])

##########################################################
# Quality control
##########################################################
qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, Inf),
            length_thresh = c(20, Inf), mapp_thresh = 0.9,
            gc_thresh = c(20, 80))
Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc
ref_qc <- qcObj$ref_qc; qcmat <- qcObj$qcmat; gc_qc <- ref_qc$gc
write.table(qcmat, file = paste(projectname, '_qcmat', '.txt', sep=''),
            sep = '\t', quote = FALSE, row.names = FALSE)

##########################################################
# Estimating library size factor for each sample
##########################################################
Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x){!any(x==0)}),]
pseudo.sample <- apply(Y.nonzero,1,function(x){prod(x)^(1/length(x))})
N <- apply(apply(Y.nonzero, 2, function(x){x/pseudo.sample}), 2, median)
plot(N, apply(Y,2,sum), xlab='Estimated library size factor', ylab='Total sum of reads')

##########################################################
# Genome-wide normalization using normalize_null
##########################################################
#"If there are negative control samples, use normalize_codex2_ns()"
#"If there are negative control regions, use normalize_codex2_nr()"
normObj.null <- normalize_null(Y_qc = Y_qc, gc_qc = gc_qc, K = 1:4, N = N)
Yhat <- normObj.null$Yhat
AIC <- normObj.null$AIC; BIC <- normObj.null$BIC
RSS <- normObj.null$RSS


##########################################################
# Number of latent factors
##########################################################
choiceofK(AIC, BIC, RSS, K = 1:4 , filename = "codex2_null_choiceofK.pdf")
par(mfrow = c(1, 3))
plot(1:4, RSS, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:4, AIC, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:4, BIC, type = "b", xlab = "Number of latent variables", pch=20)
par(mfrow = c(1,1))

##########################################################
# CBS segmentation per gene: optinmal for targeted seq
##########################################################
source('segment_targeted.R')
optK=which.max(BIC)
finalcall=matrix(ncol=14,nrow=0)
colnames(finalcall)=c('sample_name','chr','gene','cnv',
                      'st_bp','ed_bp','length_kb',
                      'st_exon','ed_exon','raw_cov',
                      'norm_cov','copy_no','lratio',
                      'mBIC')
for(genei in unique(ref_qc$gene)){
  cat('Segmenting gene',genei,'\n')
  geneindex=which(ref_qc$gene==genei)
  yi=Y_qc[geneindex,, drop=FALSE]
  yhati=Yhat[[optK]][geneindex,, drop=FALSE]
  refi=ref_qc[geneindex]
  finalcalli=segment_targeted(yi, yhati, sampname_qc, refi, genei, lmax=length(geneindex), mode='fraction')
  finalcall=rbind(finalcall,finalcalli)
}
cn=(as.numeric(as.matrix(finalcall[,'copy_no'])))
cn.filter=(cn<=1.7)|(cn>=2.3) # removing calls with fractional copy numbers close to 2 (for heterogeneous cancer samples)
finalcall=finalcall[cn.filter,]
length_exon=as.numeric(finalcall[,'ed_exon'])-as.numeric(finalcall[,'st_exon'])+1
finalcall=cbind(finalcall[,1:7],length_exon,finalcall[,10:14])

write.table(finalcall, file = paste( projectname,'_', optK, '_CODEX_frac.txt',
sep=''), sep='\t', quote=F, row.names=F)`

**Comment by vigneshravi** [comment]
Hello @yuchaojiang , I have updated the log and script. Following up on this request.

**Comment by yuchaojiang** [comment]
Sorry for the late reply. At which step did you get the error?

**Comment by yuchaojiang** [comment]
Okay I will close this. If you still need assistance, feel free to reopen it.

**Comment by vigneshravi** [comment]
Hello @yuchaojiang Sorry for the late response. 
I am still getting the same error at the segmentation step - segment_targeted.R  

The normalization step got over successfully

> Computing normalization with k = 4 latent factors ...
> Iteration 1     beta diff =0.316        f(GC) diff =8.22e-09
> Iteration 2     beta diff =0.00428      f(GC) diff =1.8e-12
> Iteration 3     beta diff =0.000177     f(GC) diff =2.99e-13
> Iteration 4     beta diff =2.82e-05     f(GC) diff =1.99e-13
> Stop at Iteration 4.
> AIC4 = 1113838693.903
> BIC4 = 1113354372.847
> RSS4 = 1255.258
> 
>         AIC4 = 1319241525.452
>         BIC4 = 1318580725.596

Error in the segmentation step

> Error in eval(quote(list(...)), env) :
>  argument "chri" is missing, with no default
> Calls: segment_targeted -> cbind -> standardGeneric -> eval -> eval -> eval
> Execution halted

**Comment by bwubb** [comment]
The variable 'chri' only appears in two places in the segment_targeted.R script, the first being its assignment. 

```
chri <- as.matrix(seqnames(refi))[1]
```
Make sure this is correct and has values before you call the segment_targeted function.

```
refi=ref_qc[geneindex]
  finalcalli=segment_targeted(yi, yhati, sampname_qc, refi, genei, lmax=length(geneindex), mode='fraction') 
```

Does that refi have values?

**Comment by vigneshravi** [comment]
This is the segmentation part of the wrapper which I am using the demo file in the github page as reference. [https://github.com/yuchaojiang/CODEX2/blob/master/targeted_sequencing/CODEX2_targeted_demo.R](url)

Where should the chri definitions be added?

`source('segment_targeted.R')
optK=which.max(BIC)
finalcall=matrix(ncol=14,nrow=0)
colnames(finalcall)=c('sample_name','chr','gene','cnv',
                      'st_bp','ed_bp','length_kb',
                      'st_exon','ed_exon','raw_cov',
                      'norm_cov','copy_no','lratio',
                      'mBIC')
for(genei in unique(ref_qc$gene)){
  cat('Segmenting gene',genei,'\n')
  geneindex=which(ref_qc$gene==genei)
  yi=Y_qc[geneindex,, drop=FALSE]
  yhati=Yhat[[optK]][geneindex,, drop=FALSE]
  refi=ref_qc[geneindex]
  finalcalli=segment_targeted(yi, yhati, sampname_qc, refi, genei, lmax=length(geneindex), mode='fraction')
  finalcall=rbind(finalcall,finalcalli)
}
cn=(as.numeric(as.matrix(finalcall[,'copy_no'])))
cn.filter=(cn<=1.7)|(cn>=2.3) # removing calls with fractional copy numbers close to 2 (for heterogeneous cancer samples)
finalcall=finalcall[cn.filter,]
length_exon=as.numeric(finalcall[,'ed_exon'])-as.numeric(finalcall[,'st_exon'])+1
finalcall=cbind(finalcall[,1:7],length_exon,finalcall[,10:14])

write.table(finalcall, file = paste( projectname,'_', optK, '_CODEX_frac.txt',
sep=''), sep='\t', quote=F, row.names=F)
`

I am also using the segmentation_targeted.R from the github page [https://github.com/yuchaojiang/CODEX2/blob/master/targeted_sequencing/segment_targeted.R](url)

**Comment by bwubb** [comment]
Right, so you have downloaded that 'segmentation_targeted.R' script and you have it locally correct? It has to be in the same working directory or you need to spell out the full path for the `source`. That script has the segment_targeted() function in it. The 'chri' assignment I was referring to is within that "segmentation_targeted.R" script.

So in what you pasted...

```
...
yi=Y_qc[geneindex,, drop=FALSE]
yhati=Yhat[[optK]][geneindex,, drop=FALSE]

refi=ref_qc[geneindex] #### <-- Check this value of refi, because that is what you are passing for chri

finalcalli=segment_targeted(yi, yhati, sampname_qc, refi, genei, lmax=length(geneindex), mode='fraction')
...
```

**Comment by vigneshravi** [comment]
**function call** 
`finalcalli=segment_targeted(yi, yhati, sampname_qc, refi, genei, lmax=length(geneindex), mode='fraction')`

**segment_targeted function**
`segment_targeted <- function(yi, yhati, sampname_qc, refi, genei, chri, lmax, mode) {
  finalcall <- matrix(ncol = 10)
  lmax <- lmax - 1
  if(is.vector(yi)){
    yi=t(yi)
    yhati=t(yhati)
  }
`

So the segment_targeted function has 8 arguments while when invoked, only 7 arguments are passed in. if refi and chri is same, should I edit the function call?

**Comment by yuchaojiang** [comment]
Thanks @bwubb for your input :-)

**Comment by yuchaojiang** [comment]
@vigneshravi The segmentation function for targeted sequencing https://github.com/yuchaojiang/CODEX2/blob/master/targeted_sequencing/segment_targeted.R has only 7 arguments. Where did you get the one with chri? I think this led to the error you encountered.
