### ISSUE TITLE
Error in genome[[chrtemp]] : no such sequence

### ISSUE THREAD

**Issue by ZeyanZhang** [yuchaojiang/CODEX2#12]
Hi Yuchao,
When I tried to run the getgc function, I always get the error below. Can you please advise what's wrong? Thanks.

Getting GC content for chr 1
Getting GC content for chr 10
Getting GC content for chr 11
Getting GC content for chr 12
Getting GC content for chr 13
Getting GC content for chr 14
Getting GC content for chr 15
Getting GC content for chr 16
Getting GC content for chr 17
Getting GC content for chr 18
Getting GC content for chr 19
Getting GC content for chr 2
Getting GC content for chr 20
Getting GC content for chr 21
Getting GC content for chr 22
Getting GC content for chr 3
Getting GC content for chr 4
Getting GC content for chr 5
Getting GC content for chr 6
Getting GC content for chr 7
Getting GC content for chr 8
Getting GC content for chr 9
Getting GC content for chr M
Error in genome[[chrtemp]] : no such sequence
Calls: getgc -> unmasked -> [[ -> [[
Execution halted

Best,
Zeyan

**Comment by yuchaojiang** [comment]
Hi,

You should remove chrM from the analysis. You cannot profile copy numbers from that with high accuracy anyway.

Yuchao

**Comment by ZeyanZhang** [comment]
@yuchaojiang 
Thanks, chrM is the problem.
