### ISSUE TITLE
the meaning of the final result

### ISSUE THREAD

**Issue by N-damo** [yuchaojiang/CODEX2#13]
Dear Dr.J,
Thank you for your work in developing CODEX2. As mentioned in title, how to understand the title 'sample_name chr cnv   st_bp   ed_bp length_kb ***st_exon ed_exon*** raw_cov norm_cov copy_no   lratio    mBIC' in the final result.?
Best regards
Li'an Lin

**Comment by yuchaojiang** [comment]
Hi,

I apologize that this was not clear. Please see below. Will update soon.

The output file is tab delimited and has 13 columns with rows corresponding to CNV events. The columns include sample name (sample names), chr (chromosome), cnv (deletion or duplication), st bp (cnv start position in base pair, the start position of the first exon in the cnv), ed bp (cnv end position in base pair, the end position of the last exon in the cnv), length kb (CNV length in kb), st exon (the first exon after QC in the cnv, integer value numbered in qcObj$ref qc), ed exon (the last exon after QC in the cnv, integer value numbered in qcObj$ref qc), raw cov (raw coverage), norm cov (normalized coverage), copy no (copy number estimate), lratio (likelihood ratio of CNV event versus copy neutral event), mBIC (modified BIC value, used to determine the stop point of segmentation).
