### ISSUE TITLE
how to set sampname_qc correctly

### ISSUE THREAD

**Issue by N-damo** [yuchaojiang/CODEX2#14]
I followed the pipeline provided in <http://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html>. The output result  like 
![image](https://user-images.githubusercontent.com/43883112/60159102-0533bf00-9825-11e9-9bb9-1a416d81e0a9.png). Obviously, it miss the true sample name,how do i fix it or how to set sampname_qc parameter correctly?

`finalcall.CBS <- segmentCBS(Y_qc[chr.index,],  # recommended
                            Yhat.ns, optK = which.max(BIC.ns),
                            K = 1:5,
                            sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")`

**Comment by bwubb** [comment]
Change this `sampname_qc = paste('sample',1:ncol(Y_qc),sep='')`

You can replace it with `sampname_qc=colnames(Y_qc)`

**Comment by N-damo** [comment]
thanks, CODEX2 really achieves a good performance for both common and rare CNV.

**Comment by yuchaojiang** [comment]
Thanks @bwubb ! Will push the update shortly. 
And @N-damo glad codex2 is working well :-)
