### ISSUE TITLE
segmentCBS error

### ISSUE THREAD

**Issue by nicokrez** [yuchaojiang/CODEX2#16]
Hi,

I am using the software on WES samples using h38.
The hole software runs well until this part:

```
> finalcall.CBS <- segmentCBS(Y_qc[chr.index,],
+                             Yhat, optK = which.max(BIC),
+                             K = 1:5,
+                             sampname_qc = sampname_qc,
+                             ref_qc = ranges(ref_qc)[chr.index],
+                             chr = chr, lmax = 400, mode = "integer")
Segmenting sample 1: WES_val18_1..
Error in rep(1:num, rep(lmax, num)) : invalid 'times' argument
```

First I tried 60 samples, in a second test I only used 7 samples.
Any ideas why I am getting this error?

Thank you for your help and kind regards,
Nicolas

**Comment by yuchaojiang** [comment]
Hi,

Can you send your save.image(file=’test.rda’) and we would take a look? Please don’t include any sample identifier and rename your samples if necessary.

Thanks!

**Comment by nicokrez** [comment]
Hi,

thank you for your quick reply.
Where should I upload the file?
On the main page the "upload files" button is not working.
"Uploads are disabled.
File uploads require push access to this repository."

Best.

**Comment by yuchaojiang** [comment]
Hi,

Can you put it in Dropbox or Google drive and share the link?

Yuchao

On Aug 16, 2019, at 3:00 AM, nicokrez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

thank you for your quick reply.
Where should I upload the file?
On the main page the "upload files" button is not working.
"Uploads are disabled.
File uploads require push access to this repository."

Best.

**Comment by nicokrez** [comment]
Hi,

here is the link to the file in google drive:

https://drive.google.com/open?id=17lH9Jywnx_KDl46xxlFx8oi5wIKaOOge

Best.

**Comment by yuchaojiang** [comment]
This should help solve your error.


`
chr=18
chr.index <- which(seqnames(ref_qc)==chr)

Yhat.chr=Yhat
for(k in 1:4){
  Yhat.chr[[k]]=Yhat[[k]][chr.index,]
}

finalcall.CBS <- segmentCBS(Y_qc[chr.index,],
                            Yhat.chr, optK = which.max(BIC),
                            K = 1:4,
                            sampname_qc = sampname_qc,
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")


`
