### ISSUE TITLE
Difference between getmapp.R and mapp.R

### ISSUE THREAD

**Issue by zcsheng95** [yuchaojiang/CODEX2#18]
I noticed there two different versions of function for calculating mappability and they take different inputs as arguments. What is the difference between those two? If I am using mouse genome, which one should I use?

Thanks

**Comment by yuchaojiang** [comment]
If it is mm9/mm10, you should use mapp.R (https://github.com/yuchaojiang/CODEX2/blob/master/mouse/mapp.R). It is not a function but rather a script to get mappability from your Granges object.

See also under here https://github.com/yuchaojiang/CODEX2#codex2-for-mouse-genome

**Comment by zcsheng95** [comment]
Thanks. Actually I am using mm10 and I realize getmapp function exported by the package is not able to recognize it.
So I guess calling computemapp function from mapp.R then loop over all the chromosomes will do the work?

**Comment by yuchaojiang** [comment]
Yes. Feel free to parallelize it as well -- it's not very efficient as a byproduct of the package...
