### ISSUE TITLE
CODEX2 for low coverage WGS

### ISSUE THREAD

**Issue by DadongZ** [yuchaojiang/CODEX2#19]
We have a low pass WGS data set and I found none of them can pass the sd threshold during normalization:
`nonCNV.index=apply(z.codex,1,sd) < 0.15`

```
summary(apply(z.codex,1,sd))
Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.2869  0.5146  0.5487  0.5481  0.5822  0.736
```

What might be the concerns to increase the sd's threshold? say at median=0.55 or other fixed threshold?

The low coverage issue also found in the qc step where 104221 out of 135087 exons were excluded. (102876 due to extreme low coverage), I seem have to reduce the minimum coverage threshold as well. Any suggestions for it?

**Comment by yuchaojiang** [comment]
Hi,

It seems that you need to zoom out (ie adopt a larger bin size). The noise dominates for now. Also, if you don’t have negative controls, you don’t necessarily need to use the force calling algorithm. It’s useful only if you want to recover the common CNV signals.

Yuchao

**Comment by DadongZ** [comment]
Thanks for your prompt reply.
Which function did you refer for `force calling algorithm`?
I have generated a bed file (hg38) using a bin size 1000. Did you mean to increase the size? say 10000?

Our samples are pre/post study and I wanted to run 1) using pre as control 2) independently without controls for pre samples (n=40) and post samples (n=40). Does it make sense?

**Comment by yuchaojiang** [comment]
Without looking at your data, it's hard to give a bin size that is appropriate.

For 1), you should use https://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html#running-codex2-with-negative-control-samples

For 2), you should start with https://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html#running-codex2-without-specifying-negative-control-samplesregions
This is CODEX2 without force calling. It's still an enhanced version of CODEX.
