### ISSUE TITLE
CODEX2, getbambed, wrong example

### ISSUE THREAD

**Issue by thedam** [yuchaojiang/CODEX2#2]
Hi,
in the example here:
https://github.com/yuchaojiang/CODEX2/blob/master/targeted_sequencing/codex2_targeted.R#L15-L20
there's an error when running this code:
`library(CODEX2)`
```
chr=1
# get bam directories, read in bed file, get sample names
bambedObj=getbambed(bamdir=bamdir,
                    bedFile=bedFile,
                    sampname=sampname,
                    projectname=projectname,chr)
```

> Error in getbambed(bamdir = bamdir, bedFile = bedFile, sampname = sampname,  : 
>   unused argument (chr)

Should I use getbambed from CODEX?

EDIT: in the whole example file "codex2_targeted.R" the commands from CODEX and CODEX2 are mixed (This is my first time I use CODEX and/or CODEX2 so I'm a bit confused) 

Cheers
Damian Loska

**Comment by yuchaojiang** [comment]
chr is not needed for CODEX2. IRanges obj is substituted with GRanges
