### ISSUE TITLE
Problem running qc

### ISSUE THREAD

**Issue by kielahi** [yuchaojiang/CODEX2#21]
Hi,

I run qcObj <- qc(Y, sampname, ref, cov_thresh  = c(20, 4000), length_thresh = c(20, 2000), mapp_thresh = 0.9, gc_thresh = c(20,80))

and get the following error

Error in apply(Y_qc, 1, median) : dim(X) must have a positive length

what is the issue?

Thanks

**Comment by yuchaojiang** [comment]
It seems your Y_qc is not a matrix.

On Jun 30, 2020, at 1:05 PM, kielahi <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

I run qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, 4000), length_thresh = c(20, 2000), mapp_thresh = 0.9, gc_thresh = c(20,80))

and get the following error

Error in apply(Y_qc, 1, median) : dim(X) must have a positive length

what is the issue?

Thanks

**Comment by kielahi** [comment]
Ok, because y_qc is calculated by the function and not me, why would that be the case?

**Comment by yuchaojiang** [comment]
This function is very simple and has been extensively used by ourselves and by other users. You should be able to figure this out yourself.

On Jul 1, 2020, at 11:30 AM, kielahi <notifications@github.com> wrote:

﻿

Ok, because y_qc is calculated by the function and not me, why would that be the case?

**Comment by a113n** [comment]
Do you have one sample only? I ran into the same issue as well. I guess you need multiple samples.

**Comment by yuchaojiang** [comment]
Yes, it adopts a cross-sample Poisson model for normalization and needs at least 10-20 samples.
