### ISSUE TITLE
First Pass - Normalizing Step - Error in smooth.spline

### ISSUE THREAD

**Issue by ReWeda** [yuchaojiang/CODEX2#22]
Dear Developer,

First, I'd like to thank you for all your efforts.

I sequenced some specific regions of chromosome 2, 5 and 12 using a custom panel. So my goal is to call CNV from targeted sequencing data.
```
n. Regions: some 3600
n, Samples: 16
Reference: HG38
R version: 3.6.3
```
I easily go through your demo (that perfectly fulfill my needs) up to the **normalization step**
Now, I designed my panel in order to use sequenced regions in chromosomes 2 and 5 as negative control region. 

Despite this, I'd like to go for a 2-pass run calling CNV without considering negative control regions first. In this way, I can figure out exactly which regions on chromosome 12 I've to use as _cnv_index_ in the second  run.

I faced a problem trying to normalize my data without considering negative control regions.
This command:
```
chr <- 'chr12'
chr.index <- which(seqnames(ref_qc)==chr)
normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                               gc_qc = gc_qc[chr.index],
                               K = 1:5, N = N)
```
returns:
```
Computing normalization with k = 1 latent factors ...
Error in smooth.spline(gc_qc, z) : 
  'tol' must be strictly positive and finite
In addition: Warning message:
In matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N, byrow = TRUE) :
  data length exceeds size of matrix
```

After a little bit of debugging, I found that, due to problems with the library or during amplification phase, I totally missed some of the regions I was expecting to cover (some 50 small regions). I thought that maybe 0s in the coverage matrix were causing the problem.
I removed them but I still get the error message.

Am I missing something?

Thanks in advance,
Davide

**Comment by yuchaojiang** [comment]
Hi Davide,

Sorry for my late reply. It's hard for me to tell exactly what might have gone wrong.  It could be because of the zeros. Can you send some more details? If you want us to look into the details, some rda file may be needed.

Yuchao

**Comment by ReWeda** [comment]
Hi Yuchao,

First of all, thanks for your answer. 
I already tried to remove regions in the bed file that result in zeros in the coverage matrix but this operation didn't solve the error.
I attach to this message the .rda file and the R code I'm currently using to run your tool (zipped).
**R Data Structure saved in the .rda file have been created using my original bed file (all regions included)**

Davide
Attachment : [ForYuchao.zip](https://github.com/yuchaojiang/CODEX2/files/5188943/ForYuchao.zip)

**Comment by yuchaojiang** [comment]
Hi Davide,

I am sorry but this fell through the cracks. I am closing this issue given how long it is, but if you still need help, please feel free to reopen this and leave a comment.

Thanks,
Yuchao

**Comment by MaxSimonNm** [comment]
Hello Yuchao,

Thank you for making this tool.
I am having an issue with a particular section of  [CODEX2.Rmd](https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.Rmd): 

## Running CODEX2 without specifying negative control samples/regions

Y_qc and gc_qc can be obtained from the sequencing bam files using the code in the previous section.

```{r, message=FALSE}
chr <- 20 # This can be run for one chromosome or multiple chromosomes
chr.index <- which(seqnames(ref_qc)==chr)
normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                               gc_qc = gc_qc[chr.index],
                               K = 1:5, N = N)
Yhat.null <- normObj.null$Yhat
AIC.null <- normObj.null$AIC; BIC.null <- normObj.null$BIC
RSS.null <- normObj.null$RSS
```
At line:
```{r, message=FALSE}
normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                               gc_qc = gc_qc[chr.index],
                               K = 1:5, N = N)
```
I am getting the following error:
```{r, message=FALSE}
> normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
+                                gc_qc = gc_qc[chr.index],
+                                K = 1:5, N = N)
Error in smooth.spline(gc_qc, z) : 
  'tol' must be strictly positive and finite
In addition: Warning messages:
1: In matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N, byrow = TRUE) :
  non-empty data for zero-extent matrix
2: In matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N, byrow = TRUE) :
  non-empty data for zero-extent matrix
```
#### Please note that I am completely following the CODEX2.Rmd. I am not using any outside datasets.

**Comment by yuchaojiang** [comment]
You need to check whether you have any NAs in your GC content vector.
