### ISSUE TITLE
BSgenome problem

### ISSUE THREAD

**Issue by dongleihu** [yuchaojiang/CODEX2#24]
I was following commands in the [manual](https://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html#pre-computation-and-quality-control).  Everything was fine until this command `mapp <- getmapp(ref, genome = genome)`.  I got an error message: Error in getmapp(ref, genome = genome) :
  no slot of name "provider_version" for this object of class "BSgenome".

Thanks for any advice!

**Comment by yuchaojiang** [comment]
Can you send your full script and output?

On Feb 24, 2021, at 8:39 PM, Donglei Hu <notifications@github.com<mailto:notifications@github.com>> wrote:



I was following commands in the manual<https://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html#pre-computation-and-quality-control>. Everything was fine until this command mapp <- getmapp(ref, genome = genome). I got an error message: Error in getmapp(ref, genome = genome) :
no slot of name "provider_version" for this object of class "BSgenome".

Thanks for any advice!

**Comment by dongleihu** [comment]
Here are my codes.

`library(CODEX2)

library(WES.1KG.WUGSC) 
dirPath <- system.file("extdata", package = "WES.1KG.WUGSC")
bamFile <- list.files(dirPath, pattern = '*.bam$')
bamdir <- file.path(dirPath, bamFile)
sampname <- substr(bamFile,1,7)
bedFile <- file.path(dirPath, "chr22_400_to_500.bed")
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile,
                       sampname = sampname, projectname = "CODEX2_demo")
bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
ref <- bambedObj$ref; projectname <- bambedObj$projectname
genome = BSgenome.Hsapiens.UCSC.hg19
gc <- getgc(ref, genome = genome)
mapp <- getmapp(ref, genome = genome)`

After the last command, I got the error message: Error in getmapp(ref, genome = genome) :
no slot of name "provider_version" for this object of class "BSgenome".

Thanks!

**Comment by yuchaojiang** [comment]
Hi, 

It's hard to tell. Most likely you have problems loading the BSgenome hg38 or hg19 package. This part of the code has been used and tested very frequently and I don't think it's something with regard to codex2.

**Comment by karynne7** [comment]
I get the same error, maybe we're missing a required package? I'm using R version 4.0.3

**Comment by karynne7** [comment]
I'm getting the same thing. Looks like it's a deprecation issue. 
>providerVersion(genome)
[1] "hg19"
Warning message:
  Using providerVersion() on a BSgenome object is deprecated. Please use
  'metadata(x)$genome' instead. 
> metadata(genome)$genome
[1] "hg19"

And in CODEX2/package/R/getmapp.R:
"  if(genome@provider_version == 'hg19'){mapp_gref = mapp_hg19}
  if(genome@provider_version == 'hg38'){mapp_gref = mapp_hg38}"

Can we update these? 
Thanks

**Comment by yuchaojiang** [comment]
Hi @karynne7 Thanks for your suggestion. I just ran on R 4.0.4 and I don't have this problem. Can you let me know your R version, and which BSgenome package you loaded?

**Comment by dongleihu** [comment]
@yuchaojiang I am using R 4.0.4 too but I got the problem with BSgenome.Hsapiens.UCSC.hg19.

**Comment by yuchaojiang** [comment]
Okay I will look into this when I have more bandwidth. For now, you can just use a new getmapp function where you change

***@***.***_version == 'hg19'){mapp_gref = mapp_hg19}
***@***.***_version == 'hg38'){mapp_gref = mapp_hg38}

to


if(metadata(genome)$genome == 'hg19'){mapp_gref = mapp_hg19}
if(metadata(genome)$genome == 'hg38'){mapp_gref = mapp_hg38}

This should work for you.

On Mar 15, 2021, at 6:37 PM, Donglei Hu ***@***.******@***.***>> wrote:



@yuchaojiang<https://github.com/yuchaojiang> I am using R 4.0.4 too but I got the problem with BSgenome.Hsapiens.UCSC.hg19.

**Comment by karynne7** [comment]
I did change it and it solved the problem for me. Thanks!
