### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by MaxSimonNm** [yuchaojiang/CODEX2#27]
Hello Dr Yuchao

I am having a few issues while running CODEX2. I have not used CODEX before and am unfamiliar with the Poisson model. I am sorry if i am asking some apparent questions.

My situation is this: I have 2 Truth Samples (samples whose CNV details I know are correct). I have a test batch of 35 samples.
I have run CODEX2 in these manners:
**Run 1:**
Sample BAMs taken - 35 from test batch | K = 1:5  | chr: 17
Output:

  | sample_name | chr | cnv | st_bp | ed_bp | length_kb | st_exon | ed_exon | raw_cov | norm_cov | copy_no | lratio | mBIC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cnv1 | Sample 1 | chr17 | dup | 7687395 | 7689351 | 1.957 | 1307 | 1311 | 474 | 341 | 3 | 21.683 | 4.216
cnv2 | Sample 1 | chr17 | del | 19348563 | 19353709 | 5.147 | 799 | 800 | 49 | 104 | 1 | 18.038 | 4.88
cnv3 | Sample 3 | chr17 | dup | 3094629 | 3121197 | 26.569 | 1150 | 1156 | 2117 | 1548 | 3 | 84.334 | 66.263
cnv4 | Sample 3 | chr17 | dup | 28673501 | 28681954 | 8.454 | 874 | 875 | 206 | 129 | 3 | 19.022 | 68.109
cnv5 | Sample 4 | chr17 | dup | 73626838 | 73627110 | 0.273 | 532 | 533 | 604 | 446 | 3 | 21.891 | 4.485
cnv6 | Sample 4 | chr17 | dup | 19348563 | 19353709 | 5.147 | 799 | 800 | 389 | 279 | 3 | 18.219 | 5.588
cnv7 | Sample 6 | chr17 | del | 41209048 | 41215988 | 6.941 | 210 | 212 | 252 | 443 | 1 | 46.84 | 29.398

**Run 2:**
Sample BAMs taken - 35 from test batch | K = 1:10  | chr: 17
Output:

  | sample_name | chr | cnv | st_bp | ed_bp | length_kb | st_exon | ed_exon | raw_cov | norm_cov | copy_no | lratio | mBIC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cnv1 | Sample 1 | chr17 | dup | 7687395 | 7689351 | 1.957 | 1307 | 1311 | 474 | 341 | 3 | 21.683 | 4.216
cnv2 | Sample 1 | chr17 | del | 19348563 | 19353709 | 5.147 | 799 | 800 | 49 | 104 | 1 | 18.038 | 4.88
cnv3 | Sample 3 | chr17 | dup | 3094629 | 3121197 | 26.569 | 1150 | 1156 | 2117 | 1548 | 3 | 84.334 | 66.263
cnv4 | Sample 3 | chr17 | dup | 28673501 | 28681954 | 8.454 | 874 | 875 | 206 | 129 | 3 | 19.022 | 68.109
cnv5 | Sample 4 | chr17 | dup | 73626838 | 73627110 | 0.273 | 532 | 533 | 604 | 446 | 3 | 21.891 | 4.485
cnv6 | Sample 4 | chr17 | dup | 19348563 | 19353709 | 5.147 | 799 | 800 | 389 | 279 | 3 | 18.219 | 5.588
cnv7 | Sample 6 | chr17 | del | 41209048 | 41215988 | 6.941 | 210 | 212 | 252 | 443 | 1 | 46.84 | 29.398

**Run 3:**
Sample BAMs taken - 35 from test batch   | K = 1:5 | chr: 13 and 17
Output:

  | sample_name | chr | cnv | st_bp | ed_bp | length_kb | st_exon | ed_exon | raw_cov | norm_cov | copy_no | lratio | mBIC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cnv1 | Sample 1 | chr13 | dup | 7687395 | 7689351 | 1.957 | 903 | 905 | 317 | 218 | 3 | 19.527 | 3.53
cnv2 | Sample 1 | chr17 | dup | 78403552 | 78410018 | 6.467 | 581 | 582 | 167 | 97 | 3 | 19.21 | 6.351
cnv3 | Sample 4 | chr13 | dup | 67647500 | 68331876 | 684.377 | 217 | 219 | 715 | 538 | 3 | 20.896 | 4.269
cnv4 | Sample 4 | chr17 | del | 10278985 | 10284601 | 5.617 | 924 | 925 | 122 | 208 | 1 | 19.442 | 8.308
cnv5 | Sample 4 | chr13 | dup | 75485511 | 75489741 | 4.231 | 228 | 229 | 439 | 319 | 3 | 18.492 | 11.985

**Run 4:**
Sample BAMs taken - 18 from test batch and 2 Truth Sample (named TS1 and TS2)  | K = 1:20 | All Chr
Output:

  | sample_name | chr | cnv | st_bp | ed_bp | length_kb | st_exon | ed_exon | raw_cov | norm_cov | copy_no | lratio | mBIC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cnv1 | TS1 | chr1 | del | 14862604 | 153993261 | 139130.658 | 791 | 836 | 6452 | 9534 | 1 | 295.137 | 279.455
cnv2 | TS2 | chr1 | dup | 14862604 | 153230197 | 138367.594 | 791 | 833 | 13222 | 10416 | 3 | 152.839 | 136.733
cnv3 | Sample 2 | chr1 | del | 14862604 | 154221443 | 139358.84 | 791 | 838 | 5468 | 10091 | 1 | 1255.645 | 1247.018
cnv4 | Sample 4 | chr1 | dup | 45609814 | 50117179 | 4507.366 | 558 | 559 | 269 | 182 | 3 | 18.066 | 1.993
cnv5 | Sample 5 | chr1 | dup | 151849769 | 151900169 | 50.401 | 353 | 354 | 820 | 601 | 3 | 31.968 | 15.849

**Run 5:**
Sample BAMs taken - 18 from test batch and 2 Truth Sample (named TS1 and TS2)  | K = 1:5 | chr 17
Output:

  | sample_name | chr | cnv | st_bp | ed_bp | length_kb | st_exon | ed_exon | raw_cov | norm_cov | copy_no | lratio | mBIC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cnv1 | Sample 4 | chr17 | dup | 5036717 | 5041065 | 4.349 | 127 | 131 | 980 | 755 | 3 | 19.839 | 2.346
cnv2 | Sample 4 | chr17 | dup | 8480533 | 8508320 | 27.788 | 305 | 307 | 301 | 205 | 3 | 19.54 | 4.606
cnv3 | Sample 4 | chr17 | dup | 36874077 | 36875856 | 1.78 | 590 | 591 | 751 | 574 | 3 | 17.492 | 5
cnv4 | Sample 6 | chr17 | del | 41209048 | 41215988 | 6.941 | 802 | 804 | 252 | 440 | 1 | 45.34 | 27.665

I am not able to get concurrent results from the above outputs.

- I am getting the same output in Run 1 and Run 2, even if there is a change in K.
- In Run 3, when I introduce 2 chromosomes, Chr 13 and 17, the output doesn't contain some of the observed events in Run 1 and 2.
- In Run 4, Output states TS1 has del and TS2 has dup in Chr 1, which does not match the True CNV output.
- In Run 5, when I only mention Chr 17, the output doesn't consider the BRCA1 deletion present in TS1, as per the True CNV output.

The **code** is as follows:
```
#Preprocessing ####
library(CODEX2)

# Set the path to the directory containing the BAM files 
dirPath = file.path('','home','bioinfo','Nilesh','CODEX2','Attempt_18B_Truth')

# Get the names of all BAM files in the directory
bamFile <- list.files(dirPath, pattern = '*.bam$')

# Create a new path by combining the directory path and the BAM file names
bamdir <- file.path(dirPath, bamFile)

# Extract the sample name from the BAM file name
sampname <- substr(bamFile,1,4)

# Set the path to the BED file
bedFile <- file.path(dirPath, "test_codex.bed")

# Create an object containing the BAM, BED, sample name, and project name
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, 
                       sampname = sampname, projectname = "CODEX2_18B-Truth")

# Extract the BAM directory, sample name, reference, and project name from the object
bamdir <- bambedObj$bamdir
sampname <- bambedObj$sampname
ref <- bambedObj$ref
projectname <- bambedObj$projectname
#------------------------------------------------------------------------------#

#GC Content and Mappability ####
genome = BSgenome.Hsapiens.UCSC.hg19 #hg19
#-- Defining Funcion getgc --#
# Define a function to calculate the GC content of a set of genomic ranges
getgc = function (ref, genome = NULL) {
  # If the genome argument is NULL, set it to the hg19 genome
  if(is.null(genome)){genome = BSgenome.Hsapiens.UCSC.hg19}
  
  # Create an empty vector to store the GC content for each range
  gc = rep(NA, length(ref))
  
  # Loop over each unique chromosome in the input ranges
  for (chr in unique(seqnames(ref))) {
    # Print a message to show which chromosome we are currently processing
    message("Getting GC content for chr ", chr, sep = "")
    
    # Get the indices of all ranges on the current chromosome
    chr.index = which(as.matrix(seqnames(ref)) == chr)
    
    # Create a new set of ranges that only includes the ranges on the current chromosome
    ref.chr = IRanges(start = start(ref)[chr.index], end = end(ref)[chr.index])
    
    # Check if the current chromosome is the X or Y chromosome and set the chrtemp variable accordingly
    if (chr == "X" | chr == "x" | chr == "chrX" | chr == "chrx") {
      chrtemp <- 'X'
    } else if (chr == "Y" | chr == "y" | chr == "chrY" | chr == "chry") {
      chrtemp <- 'Y'
    } else {
      chrtemp <- as.numeric(mapSeqlevels(as.character(chr), "NCBI")[1])
    }
    
    # If the current chromosome cannot be found in the NCBI Homo sapiens database, print a warning message
    if (length(chrtemp) == 0) message("Chromosome cannot be found in NCBI Homo sapiens database!")
    
    # Get the unmasked sequence for the current chromosome from the genome
    chrm <- unmasked(genome[[paste('chr',chrtemp,sep='')]])
    
    # Create a new set of sequences from the genome that only includes the ranges on the current chromosome
    seqs <- Views(chrm, ref.chr)
    
    # Calculate the base frequency for each range on the current chromosome
    af <- alphabetFrequency(seqs, baseOnly = TRUE, as.prob = TRUE)
    
    # Calculate the GC content for each range on the current chromosome
    gc[chr.index] <- round((af[, "G"] + af[, "C"]) * 100, 2)
  }
  
  # Return the GC content vector
  gc
}
#-- getgc Function end --#
# Calculate the GC content of the input ranges
gc <- getgc(ref, genome = genome)

# Calculate the mappability of the input ranges
mapp <- getmapp(ref, genome = genome)

# Create a vector of gene names for each range
gene = rep(NA, length(ref))

# Loop over each unique chromosome in the input ranges
for (chr in as.matrix(unique(seqnames(ref)))) {
  # Get the indices of all ranges on the current chromosome
  chr.index = which(seqnames(ref) == chr)
  
  # Generate a gene name for each range on the current chromosome by concatenating the chromosome name, 
  # the string "_gene_", and the index of the range divided by 30 and rounded up
  gene[chr.index] = paste(chr, '_gene_', ceiling(chr.index / 30), sep = '')
}

# Update the input ranges to include the GC content, mappability, and gene name for each range
values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene))
#------------------------------------------------------------------------------#

#Raw read Depth ####
# Calculate the coverage of the alignments
coverageObj <- getcoverage(bambedObj, mapqthres = 20)

# Get the coverage matrix from the coverage object
Y <- coverageObj$Y

# Write the coverage matrix to a CSV file
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)

# Print the first four columns of the coverage matrix
head(Y[,1:4])

#------------------------------------------------------------------------------#

#Quality Control ####
# Perform quality control on the alignment data
qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, 4000),
            length_thresh = c(20, 2000), mapp_thresh = 0.9,
            gc_thresh = c(20, 80))

# Get the filtered coverage matrix, sample names, and genomic ranges from the qc object
Y_qc <- qcObj$Y_qc
sampname_qc <- qcObj$sampname_qc
ref_qc <- qcObj$ref_qc
qcmat <- qcObj$qcmat; gc_qc <- ref_qc$gc

# Write the quality control matrix to a file
write.table(qcmat, file = paste(projectname, '_qcmat', '.txt', sep=''),
            sep = '\t', quote = FALSE, row.names = FALSE)

#------------------------------------------------------------------------------#

#Estimating library size factor for each sample ####
# Create a matrix of non-zero values from the quality-controlled coverage data
Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x){!any(x==0)}),]

# Calculate the pseudo-sample median for each row in the non-zero matrix
pseudo.sample <- apply(Y.nonzero,1,function(x){exp(1/length(x)*sum(log(x)))})

# Divide each column in the non-zero matrix by the corresponding value in the pseudo-sample vector
# and take the median of the resulting values
N <- apply(apply(Y.nonzero, 2, function(x){x/pseudo.sample}), 2, median)

# Create a scatter plot of N against the total sum of reads in each sample
# and save the plot as a PDF file
pdf("Batch_Library_Size_Factor.pdf")
plot(N, apply(Y,2,sum), xlab='Estimated library size factor', ylab='Total sum of reads')
dev.off() 
#------------------------------------------------------------------------------#

#Running CODEX2 without specifying negative control samples/regions ####
# This can be run for One chromosome 
chr <- 'chr17'
#Or for Multiple chromosomes
#c('chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10','chr11','chr12','chr13','chr14','chr15','chr16','chr17','chr18','chr19','chr20','chr21','chr22','chrX','chrY')

chr.index <- which(seqnames(ref_qc)==chr)
normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                               gc_qc = gc_qc[chr.index],
                               K = 1:5, N = N)
Yhat.null <- normObj.null$Yhat
AIC.null <- normObj.null$AIC; BIC.null <- normObj.null$BIC
RSS.null <- normObj.null$RSS

#Choose the number of latent Poisson factors. BIC is used as the model selection metric by default. 
choiceofK(AIC.null, BIC.null, RSS.null, K = 1:5, filename = "codex2_null_choiceofK_1-5_for_18B-Truth_chr17.pdf")
#------------------------------------------------------------------------------#

#Running segmentation by CODEX2 ####
finalcall.CBS <- segmentCBS(Y_qc[chr.index,],  # recommended
                            Yhat.null, optK = which.max(BIC.null),
                            K = 1:5,
                            sampname_qc = colnames(Y_qc),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
#------------------------------------------------------------------------------#

#Exporting Results ####
write.csv(finalcall.CBS, "./finalcall_CBS_K1-5_for_18B-Truth_chr17.csv", row.names = TRUE)
```

**1** Could you explain what I am doing wrong?

**2** I observed that there are two versions of the code equation for pseudo.sample, as highlighted below:
https://github.com/yuchaojiang/CODEX2/blob/6fb70da9bd07a5c831308ba425efc5988db0cabf/targeted_sequencing/CODEX2_targeted_demo.R#L54
https://github.com/yuchaojiang/CODEX2/blob/6fb70da9bd07a5c831308ba425efc5988db0cabf/demo/CODEX2.Rmd#L108

Could you explain to me the difference between the equations?

**3**  Is it possible for gene names to be taken from the bed file directly, if a gene name column is provided?

**Comment by yuchaojiang** [comment]
Hi @MaxSimonNm 

It is not expected that the call results are different if your input is different. The different samples, for example, can come from different runs/batches and this would affect how normalization captures the low-rank noise. I would suggest that you feed in all samples. Also you should manually check the selection of the optimal K. There is also a tradeoff with regard to K: larger K --> more stringent --> less calls --> lower sensitivity but higher specificity.

The two different versions of the code to calculate the library size factor are essentially the same. One is to prevent numerical overflow with the prod() function.

I don't think it's currently supported. But you can directly overlap your bed targets and the call sets using GenomicRanges.

I hope that this is helpful!
Yuchao
