### ISSUE TITLE
codex2_targeted.R, getcoverage error

### ISSUE THREAD

**Issue by thedam** [yuchaojiang/CODEX2#3]
Hi,
This function return an error:
https://github.com/yuchaojiang/CODEX2/blob/dcd1be53342c10b9100fb3eb6603228e256471ab/targeted_sequencing/codex2_targeted.R#L22

>  \> coverageObj=getcoverage(bambedObj,mapqthres=20)
> Error in message("Getting coverage for chr ", chr, sep = "") : 
>   argument "chr" is missing, with no default

```
?getcoverage
getcoverage {CODEX2}
(...)
getcoverage(bambedObj, mapqthres, chr)
```
Cheers
Damian Loska

**Comment by yuchaojiang** [comment]
This part of the code hasn't been updated in CODEX2 and we will do so ASAP. For now, can you use CODEX https://github.com/yuchaojiang/CODEX? Same section.

**Comment by thedam** [comment]
Hmm, ok, thanks for taking care.
Usually it's better firstly to solve the problem, then to close the issue - such solution is optimal, less users will be confused (and frustrated). Otherwise another users may report the same error.

Thanks!

**Comment by yuchaojiang** [comment]
Solved the incompatibility between CODEX and CODEX2. Demo code for targeted sequencing is updated and available at https://github.com/yuchaojiang/CODEX2/blob/master/targeted_sequencing/CODEX2_targeted_demo.R

Let us know if you run into any further problems or need further assistance.
