### ISSUE TITLE
Issues with qc function

### ISSUE THREAD

**Issue by mxiong2** [yuchaojiang/CODEX2#30]
Any ideas why I am getting this error?

Excluded 5316 exons due to extreme coverage.
Excluded 12333 exons due to extreme exonic length.
Excluded 12988 exons due to extreme mappability.
Excluded NA exons due to extreme GC content.
After taking union, excluded NA out of 217488 exons in QC.
Error: logical subscript contains NAs

**Comment by yuchaojiang** [comment]
Most likely you have NA in your calculated GC content. You should double check the genome / regions are correctly specified and can just remove the NA regions/exons/targets.

**Comment by mxiong2** [comment]
I checked the gc dataframe and there are no values with NA.

**Comment by yuchaojiang** [comment]
The qc function is a very simple wrapper function and this error is due to GC content. SHould be a quick sanity check and fixation
