### ISSUE TITLE
problem and question with CODEX2

### ISSUE THREAD

**Issue by pastoma85** [yuchaojiang/CODEX2#31]
Good morning,
I'm Pasquale.
I have some major issues with using CODEX.
We conducted a sequencing of only 1 ZC3H10 gene on 96 samples (controls and patients). from the trace on IGV there seems to be a CNV, so I started using the CODEX tools.
I wonder ask yoi:
- does it work even with such a small portion (about 1kb)? why is it worth testing samples?
- because if I use chr <- 12 it calculates the contents of GC and mapp, but then the rest doesn't work for me, while if I use chr <- NC_000012.12 the rest works for me but not GC and mapp??
- also this step gives me problems

qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, 4000),
             length_thresh = c(20, 2000), mapp_thresh = 0.9,
             gc_thresh = c(20, 80))
Excluded 8 exons due to extreme coverage.
Error in h(simpleError(msg, call)) :
   error in evaluating the argument 'x' in selecting a method for function 'end': argument "ref" is missing, with no default

I would be grateful if you give me some suggestions.

**Comment by yuchaojiang** [comment]
If you only have a handful of targets/exons, codex/codex2 would not be the ideal method, as they normalize across samples and across regions.
you should calculate GC content (e.g. from USCS browser) and load that if you have issues. Im not sure what NC_000012.12 is but it seems it's specific to your gene/setup.
you dont have ref.
