### ISSUE TITLE
failed in loading hg38

### ISSUE THREAD

**Issue by lmanchon** [yuchaojiang/CODEX2#33]
> library(CODEX2)
> library(BSgenome.Hsapiens.UCSC.hg38)

Attaching package: ‘BSgenome.Hsapiens.UCSC.hg38’

The following object is masked from ‘package:BSgenome.Hsapiens.UCSC.hg19’:

    Hsapiens

> # The following object is masked from ‘package:BSgenome.Hsapiens.UCSC.hg19’:  Hsapiens
>
> gc <- getgc(ref, genome = BSgenome.Hsapiens.UCSC.hg38)
Error: object 'ref' not found

**Comment by yuchaojiang** [comment]
hg38 has been loaded and masked the previously loaded hg19.
You error is due to an unspecified ref.
