### ISSUE TITLE
error with BSgenome.Hsapiens.UCSC.hg38

### ISSUE THREAD

**Issue by lmanchon** [yuchaojiang/CODEX2#34]
Hi,

chrX and chrY chromosomes do not seem to be recognized:

gc <- getgc(ref, genome = genome)
Getting GC content for chr chr1
Getting GC content for chr chr10
Getting GC content for chr chr11
Getting GC content for chr chr12
Getting GC content for chr chr13
Getting GC content for chr chr14
Getting GC content for chr chr15
Getting GC content for chr chr16
Getting GC content for chr chr17
Getting GC content for chr chr18
Getting GC content for chr chr19
Getting GC content for chr chr2
Getting GC content for chr chr20
Getting GC content for chr chr21
Getting GC content for chr chr22
Getting GC content for chr chr3
Getting GC content for chr chr4
Getting GC content for chr chr5
Getting GC content for chr chr6
Getting GC content for chr chr7
Getting GC content for chr chr8
Getting GC content for chr chr9
Getting GC content for chr chrX
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'unmasked': no such sequence
> mapp <- getmapp(ref, genome = genome)
Getting mappability for chr1
Getting mappability for chr10
Getting mappability for chr11
Getting mappability for chr12
Getting mappability for chr13
Getting mappability for chr14
Getting mappability for chr15
Getting mappability for chr16
Getting mappability for chr17
Getting mappability for chr18
Getting mappability for chr19
Getting mappability for chr2
Getting mappability for chr20
Getting mappability for chr21
Getting mappability for chr22
Getting mappability for chr3
Getting mappability for chr4
Getting mappability for chr5
Getting mappability for chr6
Getting mappability for chr7
Getting mappability for chr8
Getting mappability for chr9
Getting mappability for chrX
Getting mappability for chrY
> values(ref) <- cbind(values(ref), DataFrame(gc, mapp))
Error in FUN(X[[i]], ...) : object of type 'closure' is not subsettable

 qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, 4000),
             length_thresh = c(20, 2000), mapp_thresh = 0.9,
             gc_thresh = c(20, 80))
Excluded 260 exons due to extreme coverage.
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'end': argument "ref" is missing, with no default
 Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc
 ref_qc <- qcObj$ref_qc; qcmat <- qcObj$qcmat; gc_qc <- ref_qc$gc
Error in getListElement(x, i, ...) :
  IRanges objects don't support [[, as.list(), lapply(), or unlist() at
  the moment

seqnames(bambedObj$ref)
factor-Rle of length 32821 with 24 runs
  Lengths:  2605  1405  1462  1529  1069 ...  1768  1611  1386  1709   202
  Values : chr1  chr10 chr11 chr12 chr13 ... chr7  chr8  chr9  chrX  chrY
Levels(24): chr1 chr10 chr11 chr12 chr13 chr14 ... chr7 chr8 chr9 chrX chrY

**Comment by yuchaojiang** [comment]
Something wrong with the format and index of the sex chromosome. You need to run getgc and getmapp without issues before running QC. One easy solution is to remove the sex chromosome. Or you can look into the two functions. They have been tested very extensively.

**Comment by migmarbor** [comment]
Maybe same error as I have described here? https://github.com/yuchaojiang/CODEX2/issues/35
I described how to solve it!
