### ISSUE TITLE
NaNs produced

### ISSUE THREAD

**Issue by maingoc303** [yuchaojiang/CODEX2#36]
Hello CODEX2 team,
I am using Codex to run Germline CNV for the batch of samples. I encountered an issue of NANs produced and the job was not proceeded.

Log file after getting coverage for samples are below (issue happened only at chromosome 8 but not others). Can you please help to take a look at this?

> Excluded 53 exons due to extreme coverage.
Excluded 106 exons due to extreme exonic length.
Excluded 0 exons due to extreme mappability.
Excluded 23 exons due to extreme GC content.
After taking union, excluded 168 out of 6967 exons in QC.
k = 1
Iteration 1	beta diff =0.673	f(GC) diff =2.42e-08
			hhat diff =0.233
			hhat diff =0.000456
			hhat diff =0.000289
			hhat diff =0.000199
			hhat diff =0.000149
			hhat diff =0.000121
			hhat diff =0.000107
			hhat diff =0.000101
			hhat diff =9.99e-05
Iteration 2	beta diff =0.000254	f(GC) diff =2.87e-12
			hhat diff =0.233
			hhat diff =0.000391
			hhat diff =0.000245
			hhat diff =0.000172
			hhat diff =0.000132
			hhat diff =0.000111
			hhat diff =9.94e-05
Iteration 3	beta diff =4.18e-05	f(GC) diff =6.94e-13
			hhat diff =0.234
			hhat diff =0.000306
			hhat diff =0.000178
			hhat diff =0.00012
			hhat diff =9e-05
Stop at Iteration 3.
AIC1 = 139378901.359
BIC1 = 139313074.174
RSS1 = 191.074
k = 2
Iteration 1	beta diff =0.673	f(GC) diff =2.42e-08
			hhat diff =0.00384
			hhat diff =0.00179
			hhat diff =0.00156
			hhat diff =0.00177
			hhat diff =0.0016
			hhat diff =0.000968
			hhat diff =0.000497
			hhat diff =0.00027
			hhat diff =0.000165
			hhat diff =0.000112
			hhat diff =8.29e-05
Iteration 2	beta diff =0.000342	f(GC) diff =2.49e-12
			hhat diff =0.12
			hhat diff =0.119
			hhat diff =0.000935
			hhat diff =0.000615
			hhat diff =0.000402
			hhat diff =0.000268
			hhat diff =0.000185
			hhat diff =0.000134
			hhat diff =0.000102
			hhat diff =8.11e-05
Iteration 3	beta diff =4.38e-05	f(GC) diff =1.3e-12
			hhat diff =0.119
			hhat diff =0.00109
			hhat diff =0.118
			hhat diff =0.000502
			hhat diff =0.000325
			hhat diff =0.000218
			hhat diff =0.000155
			hhat diff =0.000116
			hhat diff =9.01e-05
Stop at Iteration 3.
AIC2 = 139378994.766
BIC2 = 139247340.397
RSS2 = 167.802
...
k = 9
Iteration 1	beta diff =0.673	f(GC) diff =2.42e-08
			hhat diff =0.11
			hhat diff =0.0793
			hhat diff =0.0524
			hhat diff =0.0526
			hhat diff =0.0527
			hhat diff =0.0265
			hhat diff =0.0264
			hhat diff =0.0785
			hhat diff =0.00116
			hhat diff =0.000318
			hhat diff =0.0524
			hhat diff =0.0523
			hhat diff =0.0523
			hhat diff =3.6e-05
Iteration 2	beta diff =0.000382	f(GC) diff =7.2e-13
			hhat diff =0.138
			hhat diff =0.182
			hhat diff =0.0524
			hhat diff =0.0523
			hhat diff =0.0528
			hhat diff =0.0526
			hhat diff =0.0263
			hhat diff =0.0524
			hhat diff =0.000283
			hhat diff =0.0524
			hhat diff =0.000507
Iteration 3	beta diff =3.61e-05	f(GC) diff =1.02e-13
			hhat diff =0.11
			hhat diff =0.0278
			hhat diff =0.0528
			hhat diff =0.000288
			hhat diff =0.0262
			hhat diff =0.0523
			hhat diff =7.36e-05
Stop at Iteration 3.
AIC9 = 139346667.632
BIC9 = 138754222.974
RSS9 = 76.739
k = 10
Iteration 1	beta diff =0.673	f(GC) diff =2.42e-08
			hhat diff =0.121
			hhat diff =0.14
			hhat diff =0.0472
			hhat diff =0.0942
			hhat diff =0.0472
			hhat diff =0.000418
			hhat diff =0.0705
			hhat diff =0.0928
			hhat diff =0.0707
			hhat diff =0.0242
			hhat diff =0.0473
			hhat diff =0.000274
Iteration 2	beta diff =0.000376	f(GC) diff =6.84e-13
			hhat diff =0.125
			hhat diff =0.118
			hhat diff =0.0707
			hhat diff =0.0941
			hhat diff =0.0705
			hhat diff =0.0473
			hhat diff =0.0238
			hhat diff =0.0472
			hhat diff =0.118
			hhat diff =0.0943
			hhat diff =0.0249
Iteration 3	beta diff =0.000182	f(GC) diff =4.19e-13
			hhat diff =0.13
			hhat diff =0.0944
			hhat diff =0.0475
			hhat diff =0.0474
			hhat diff =0.0706
			hhat diff =0.0706
			hhat diff =0.00278
			hhat diff =0.114
			hhat diff =0.0942
			hhat diff =0.0706
			hhat diff =0.0706
			hhat diff =0.000396
Iteration 4	beta diff =0.000165	f(GC) diff =1.08e-13
			hhat diff =0.107
			hhat diff =0.141
			hhat diff =0.106
			hhat diff =0.0946
			hhat diff =0.138
			hhat diff =0.0765
			hhat diff =0.111
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
Calls: normalize2 -> lm -> lm.fit
In addition: Warning messages:
1: glm.fit: fitted rates numerically 0 occurred 
2: glm.fit: fitted rates numerically 0 occurred 
3: glm.fit: fitted rates numerically 0 occurred 
4: step size truncated due to divergence 
5: In log(L[s, normal_index]) : NaNs produced
Execution halted>

**Comment by yuchaojiang** [comment]
Hi, I think there were some convergence issues. If your sample size is not too big, I would reduce the number of latent factors a bit. If it's too large, sometimes there were issues in estimating them through the iterative fashion as implemented in CODEX and CODEX2.
