### ISSUE TITLE
Error in if ((prob1 + prob0) == 0) { : argument is of length zero

### ISSUE THREAD

**Issue by SarahGamidor** [yuchaojiang/CODEX2#37]
Hi, 

I would greatly appreciate any help

I am using negative control regions (I have specified regions) and in the normalize_codex2_nr function I get the following error: 

error in ki = 1 /cnvi = 10 (both the "ki" and the "cnvi" changes depending on our BAM files and CODEX2targets.bed).

It gives this error:
**Error in if ((prob1 + prob0) == 0) { : argument is of length zero**
That is because in function "Estep.R" the input of "mu" and "pi" is faulty - numeric(0).
This causes things like "lambda1" and "prob1" to go bad.

BUT the reason for this is because we take "mu" and "pi" from EM.seed
Inside "normalize_codex2_nr.R":
You can see the structure of the matrix being created in lines:
EM.seed = matrix(ncol = 5, nrow = 12)
colnames(EM.seed) = c("mu", "cnvfreq", "log-lik",'pi_hat','mu_hat')
EM.seed[, 1] = c(rep(log(1/2), 4), rep(log(3/2), 4), rep(log(4/2), 4))
EM.seed[, 2] = rep(1:4/10, 3)

But we still need to fill in the remaining 3 columns ("log-lik"/"pi_hat'"/"mu_hat"). That is done in:
for (emi in 1:nrow(EM.seed)) {
...
}

Now for the error:
print(EM.seed) # 1st print
if(all(EM.seed[,4]> 0.4 & EM.seed[,4] < 0.6)){
      EM.seed=EM.seed[EM.seed[,1]<0,]
} else{
      EM.seed = EM.seed[EM.seed[, 4] <= 0.4, ]
}
print(EM.seed) # 2nd print

# 1st print
              mu cnvfreq log-lik    pi_hat     mu_hat
 [1,] -0.6931472     0.1    -Inf 0.4176183 -0.6931472
 [2,] -0.6931472     0.2    -Inf 0.4176183 -0.6931472
 [3,] -0.6931472     0.3    -Inf 0.4176183 -0.6931472
 [4,] -0.6931472     0.4    -Inf 0.4176183 -0.6931472
 [5,]  0.4054651     0.1    -Inf 0.6309025  0.4054651
 [6,]  0.4054651     0.2    -Inf 0.6309025  0.4054651
 [7,]  0.4054651     0.3    -Inf 0.6309025  0.4054651
 [8,]  0.4054651     0.4    -Inf 0.6309025  0.4054651
 [9,]  0.6931472     0.1    -Inf 0.5823817  0.6931472
[10,]  0.6931472     0.2    -Inf 0.5823817  0.6931472
[11,]  0.6931472     0.3    -Inf 0.5823817  0.6931472
[12,]  0.6931472     0.4    -Inf 0.5823817  0.6931472

# 2nd print
mu cnvfreq log-lik pi_hat mu_hat
**(empty matrix!!)**

So because all 12 rows have pi_hat > 0.4 then we get an empty matrix!

Why is that? What is wrong with our regions that all pi_hat are above 0.4 in the 10th CNV region? what can we do to overcome this?

Thanks for your help,
Sarah

**Comment by yuchaojiang** [comment]
Hi, you have both your note, R output, script, and error message mixed together. it's hard to diagnose and tell what might have gone wrong. If you only have one negative region, it won't work.

**Comment by yuchaojiang** [comment]
Feel free to reopen with a detailed log file and your script.
