### ISSUE TITLE
Error in normalize_codex2_nr 

### ISSUE THREAD

**Issue by SarahGamidor** [yuchaojiang/CODEX2#38]
Hi, 

I get this 
```
Error in Running CODEX2 in regions with common CNVs 

Error in if ((prob1 + prob0) == 0) { : argument is of length zero
```
 from the `normalize_codex2_nr `function. 

```
if(all(EM.seed[,4]> 0.4 & EM.seed[,4] < 0.6)){
      EM.seed=EM.seed[EM.seed[,1]<0,]
} else{
      EM.seed = EM.seed[EM.seed[, 4] <= 0.4, ]
}
```
it seems that the first if is false, and in the else there are no values under 4 so it ends up being an empty matrix. 

This is a print of EM.seed before the if - 

```
[1,] -0.6931472 0.1 -Inf 0.4176183 -0.6931472
[2,] -0.6931472 0.2 -Inf 0.4176183 -0.6931472
[3,] -0.6931472 0.3 -Inf 0.4176183 -0.6931472
[4,] -0.6931472 0.4 -Inf 0.4176183 -0.6931472
[5,] 0.4054651 0.1 -Inf 0.6309025 0.4054651
[6,] 0.4054651 0.2 -Inf 0.6309025 0.4054651
[7,] 0.4054651 0.3 -Inf 0.6309025 0.4054651
[8,] 0.4054651 0.4 -Inf 0.6309025 0.4054651
[9,] 0.6931472 0.1 -Inf 0.5823817 0.6931472
[10,] 0.6931472 0.2 -Inf 0.5823817 0.6931472
[11,] 0.6931472 0.3 -Inf 0.5823817 0.6931472
[12,] 0.6931472 0.4 -Inf 0.5823817 0.6931472 
```

and after the filter (else) its empty. 

I am assuming the issue is from here but perhaps its not. Have you encountered it?
(We can tell that this happens only after 9 regions (so the 10th region) - cnvi = 10)
What can we do? 

 
Thanks, 
Sarah

**Comment by yuchaojiang** [comment]
No we have not encountered this before. If your prob0 and prob1 is NA or NAN or Inf, it will be problematic, although this would not be the source I think as this EM is embedded in the main function.
What do you mean by "(We can tell that this happens only after 9 regions (so the 10th region) - cnvi = 10)"
How many regions do you have in total?

**Comment by SarahGamidor** [comment]
I have 61 control regions (ranging from 230 - 950 bp) and 219 regions for CNV analysis (ranging from 30 - 2500 bp). 

What made you choose this threshold for the filtering of the seed matrix? can it be changed? would it be right to change it?

**Comment by yuchaojiang** [comment]
I'm afraid I don't understand your question and unfortunately i don't recall the details either. If you select the negative control regions using a first pass run, yes, you need to select the threshold yourself.. Usually this works best if you have prior knowledge where the regions can be (e.g., non tumor supressors or oncogenes in the cancer setting)..
