### ISSUE TITLE
How to set parameters *_index in function normalize_codex2_nr and normalize_codex2_ns?  

### ISSUE THREAD

**Issue by shexuan** [yuchaojiang/CODEX2#5]
Hi, Is there some suggestions about how to set parameters `norm_index` or `cnv_index` in function normalize_codex2_nr and normalize_codex2_ns ?  Thanks.

**Comment by urrutiag** [comment]
Hi, thanks for your interest in CODEX2, which is a component of the MARATHON copy number and tumor phylogeny pipeline.

Please see https://github.com/yuchaojiang/MARATHON for the most complete and up to date documentation.  

cnv_index in normalize_codex2_nr is an index of common CNV regions empirically identified from the data. Please see MARATHON section 4.1.2.3. "Running CODEX2 with negative control regions" for a usage example.  We set the std dev cutoff at 0.25.

norm_index in normalize_codex2_ns is an index of control samples.  For the case-control scenario, the normal sample index is known.  Please see 4.2.3. "Running CODEX2 with negative control samples" for a usage example.

Please let us know if you have any other questions.

Thanks,
Gene Urrutia PhD
