### ISSUE TITLE
Differences between CODEX and CODEX2? 

### ISSUE THREAD

**Issue by xiucz** [yuchaojiang/CODEX2#8]
Hi, 

The CODEX page redirects me here,  and could you please tell the major differences between version one and two?

If possible, I think it is better to make an introduction of the improvements in the README documents.

Thanks a lot.

**Comment by yuchaojiang** [comment]
Hi,

Your question will be best answered by referring to our CODEX2 paper in Genome Biology https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1578-y. The major difference is the introduction of negative control samples and/or regions, which drastically improved sensitivity for common CNVs as well as retaining good specificity.

Yuchao
